config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "people#index"
  resources :people do
    resources :details
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :person
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :details, dependent: :destroy
  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: %i[ show edit update destroy ]
  before_action :set_person

  # GET /details or /details.json
  def index
    @details = @person.details
    respond_to do |format|
      format.html
      format.json { render json: @details }
    end
  end

  # GET /details/1 or GET /details/1.json
  def show
    respond_to do |format|
      format.html { render turbo_stream: turbo_stream.replace('details_frame', partial: 'details/frame', locals: { person: @person }) }
      format.json { render json: @detail }
    end
  end

  # GET /details/new
  def new
    @detail = @person.details.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details or /details.json
  def create
    @detail = @person.details.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to person_details_url(@detail.person), notice: "Detail was successfully created." }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to person_details_url(@detail), notice: "Detail was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  def destroy
    @detail.destroy!

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Detail was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    def set_person
      @person = Person.find(params[:person_id])
    end

    # Only allow a list of trusted parameters through.
    def detail_params
      params.require(:detail).permit(:title, :age, :phone, :email, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or GET /people.json
  def index
    @people = Person.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1 or GET /people/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to people_url, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to people_url, notice: "Person was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/details/_detail.html.erb
<div id="<%= dom_id detail %>">
  <h3>Details for <%= detail.person.name %>:</h3>
  <li><%= detail.title %></li>
  <li><%= detail.age %></li>
  <li><%= detail.phone %></li>
  <li><%= detail.email %></li>
  <hr>
</div>

app/views/details/_form.html.erb
<%= form_with(model: [@person, @detail]) do |form| %>
  <% if detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
        <% detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :title, style: "display: block" %>
  <%= form.text_field :title %>

  <%= form.label :age, style: "display: block" %>
  <%= form.number_field :age %>

  <%= form.label :phone, style: "display: block" %>
  <%= form.text_field :phone %>

  <%= form.label :email, style: "display: block" %>
  <%= form.text_field :email %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/details/_frame.html.erb
<%= turbo_frame_tag 'details_frame' do %>
  <%= link_to "Add New Detail", new_person_detail_path(@person), data: {turbo_frame: "_top"} %>
  <%= link_to "Edit Person", edit_person_path(@person), data: {turbo_frame: "_top"} %>
  <%= link_to "Delete Person", person_path(@person, format: :html), data: {turbo_method: :delete} %>

  <% if @person.details.any? %>
    <h3>Details for <%= @person.name %>:</h3>
    <ul>
      <% @person.details.each do |detail| %>
        <li><%= detail.title %></li>
        <li><%= detail.age %></li>
        <li><%= detail.phone %></li>
        <li><%= detail.email %></li>
        <li><%= link_to "Edit", edit_person_detail_path(@person, detail), data: {turbo_frame: "_top"} %></li>
        <%= link_to "Delete", person_detail_path(@person, detail, format: :html), data: {turbo_method: :delete} %>
        <hr>
      <% end %>
    </ul>
  <% else %>
    <p>Addition of details pending for <%= @person.name %>.</p>
  <% end %>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render "form", detail: @detail %>

<br>

<div>
  <%= link_to "Show", person_detail_path(@detail.person, @detail)%> |
  <%= link_to "Back to details", person_details_path %>
</div>

app/views/details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Details</h1>
<%= link_to "All people", people_path %>

<div id="details">
  <% @details.each do |detail| %>
    <%= render detail %>
  <% end %>
</div>

<%= link_to "New detail", new_person_detail_path %>

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render "form", detail: @detail %>

<br>

<div>
  <%= link_to "Back to details", person_details_path %>
</div>

app/views/details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @detail %>

<div>
  <%= link_to "Edit this detail", edit_detail_path(@detail) %> |
  <%= link_to "Back to details", details_path %>

  <%= button_to "Destroy this detail", @detail, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Identity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name, style: "display: block" %>
  <%= form.text_field :name %>

  </br></br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
<h4><%= person.name %></h4>
</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<h1>People</h1>
<%= link_to "New person", new_person_path %>

<div class="row">
  <div class="column">
    <div class="vertical-menu">
      <% @people.each do |person| %>
        <%= link_to person.name, person_path(person), remote: true, data: { turbo_frame: 'details_frame' } %>
      <% end %>
    </div>
  </div>
  <div class="column">
    <%= turbo_frame_tag 'details_frame' %>
    <%= turbo_stream_from 'details_frame' %>
  </div>
</div>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<h2><%= @person.name %></h2>
<%= render 'details/frame', person: @person %>